version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run: make test
      - run: make integrate
      - save_cache:
          paths:
            - "${CARGO_HOME:-~/.cargo}/registry"
            - "target"
          key: cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
